# What are Numpy and Numpy arrays?

Python objects

*  high-level number objects: integers, floating point
*  containers: lists (costless insertion and append), dictionaries (fast lookup)

Numpy provides

*  extension package to Python for multi-dimensional arrays
*  closer to hardware (efficiency)
*  designed for scientific computation (convenience)
*  Also known as array oriented computing


In [1]:
import numpy as np
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [2]:
type(a)

numpy.ndarray

In [ ]:
L = range(1000)

For example, An array containing:
*  values of an experiment/simulation at discrete time steps
*  signal recorded by a measurement device, e.g. sound wave
*  pixels of an image, grey-level or colour
*  3-D data measured at different X-Y-Z positions, e.g. MRI scan
*  ...

Why it is useful: Memory-efficient container that provides fast numerical operations.

In [3]:
L = range(1000)

In [4]:
%timeit [i**2 for i in L]

1000 loops, best of 3: 424 µs per loop


In [5]:
a = np.arange(1000)

In [6]:
%timeit a**2

The slowest run took 24.60 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.26 µs per loop


In [7]:
np.array?

In [ ]:
np.lookfor('create array')

In [ ]:
import numpy as np

# Array Creation

In [8]:
a = np.array([0, 1, 2, 3])

In [9]:
a.ndim

1

In [10]:
a.shape

(4,)

In [11]:
len(a)

4

In [12]:
b = np.array([[0, 1, 2], [3, 4, 5]])

In [13]:
b, b.ndim, b.shape, len(b)

(array([[0, 1, 2],
        [3, 4, 5]]), 2, (2, 3), 2)

In [14]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
b = np.arange(1, 9, 2)
b

array([1, 3, 5, 7])

In [ ]:
type(b)

In [16]:
b.dtype

dtype('int64')

In [17]:
from numpy import pi
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [18]:
x = np.linspace( 0, 2*pi, 100 )        # useful to evaluate function at lots of points
f = np.sin(x)

In [19]:
x

array([ 0.        ,  0.06346652,  0.12693304,  0.19039955,  0.25386607,
        0.31733259,  0.38079911,  0.44426563,  0.50773215,  0.57119866,
        0.63466518,  0.6981317 ,  0.76159822,  0.82506474,  0.88853126,
        0.95199777,  1.01546429,  1.07893081,  1.14239733,  1.20586385,
        1.26933037,  1.33279688,  1.3962634 ,  1.45972992,  1.52319644,
        1.58666296,  1.65012947,  1.71359599,  1.77706251,  1.84052903,
        1.90399555,  1.96746207,  2.03092858,  2.0943951 ,  2.15786162,
        2.22132814,  2.28479466,  2.34826118,  2.41172769,  2.47519421,
        2.53866073,  2.60212725,  2.66559377,  2.72906028,  2.7925268 ,
        2.85599332,  2.91945984,  2.98292636,  3.04639288,  3.10985939,
        3.17332591,  3.23679243,  3.30025895,  3.36372547,  3.42719199,
        3.4906585 ,  3.55412502,  3.61759154,  3.68105806,  3.74452458,
        3.8079911 ,  3.87145761,  3.93492413,  3.99839065,  4.06185717,
        4.12532369,  4.1887902 ,  4.25225672,  4.31572324,  4.37

In [ ]:
f

In [20]:
print(x)

[ 0.          0.06346652  0.12693304  0.19039955  0.25386607  0.31733259
  0.38079911  0.44426563  0.50773215  0.57119866  0.63466518  0.6981317
  0.76159822  0.82506474  0.88853126  0.95199777  1.01546429  1.07893081
  1.14239733  1.20586385  1.26933037  1.33279688  1.3962634   1.45972992
  1.52319644  1.58666296  1.65012947  1.71359599  1.77706251  1.84052903
  1.90399555  1.96746207  2.03092858  2.0943951   2.15786162  2.22132814
  2.28479466  2.34826118  2.41172769  2.47519421  2.53866073  2.60212725
  2.66559377  2.72906028  2.7925268   2.85599332  2.91945984  2.98292636
  3.04639288  3.10985939  3.17332591  3.23679243  3.30025895  3.36372547
  3.42719199  3.4906585   3.55412502  3.61759154  3.68105806  3.74452458
  3.8079911   3.87145761  3.93492413  3.99839065  4.06185717  4.12532369
  4.1887902   4.25225672  4.31572324  4.37918976  4.44265628  4.5061228
  4.56958931  4.63305583  4.69652235  4.75998887  4.82345539  4.88692191
  4.95038842  5.01385494  5.07732146  5.14078798  5.2

In [ ]:
print(f)

In [21]:
a = np.arange(6) # 1d array
print(a)

[0 1 2 3 4 5]


In [22]:
b = np.arange(12).reshape(4,3)           # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [23]:
c = np.arange(24).reshape(2,3,4)         # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:

In [24]:
d = np.arange(10000)
print(d)

[   0    1    2 ..., 9997 9998 9999]


In [25]:
e = d.reshape(100,100)
print(e)

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


# Basic Operations

Arithmetic operators on arrays apply elementwise. 
A new array is created and filled with the result.

In [3]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
a, b

(array([20, 30, 40, 50]), array([0, 1, 2, 3]))

In [4]:
c = a-b
c

array([20, 29, 38, 47])

In [5]:
b**2

array([0, 1, 4, 9])

In [29]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [30]:
a<35

array([ True,  True, False, False], dtype=bool)

the product operator * operates elementwise in NumPy arrays

In [31]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )
A*B                         # elementwise product

array([[2, 0],
       [0, 4]])

In [32]:
A.dot(B)                    # matrix product

array([[5, 4],
       [3, 4]])

In [33]:
np.dot(A, B)           # another matrix product

array([[5, 4],
       [3, 4]])

+= and *=, act in place to modify an existing array rather than create a new one.

In [34]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
print(a,b, sep='\n')

[[1 1 1]
 [1 1 1]]
[[ 0.94926871  0.53361664  0.90853382]
 [ 0.2774341   0.98807443  0.38918854]]


In [35]:
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [36]:
b += a
b

array([[ 3.94926871,  3.53361664,  3.90853382],
       [ 3.2774341 ,  3.98807443,  3.38918854]])

When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).

In [37]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
b.dtype.name
c = a+b
c

array([ 1.        ,  2.57079633,  4.14159265])

In [38]:
c.dtype.name

'float64'

# References

https://docs.scipy.org/doc/numpy-dev/user/quickstart.html